name: tda-class
channels:
  - conda-forge
  - defaults
  - plotly
dependencies: 
  - python=3.7
  - ipython
  - cython
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn  
  - ipykernel
  - dionysus
  - gudhi
  - pip 
  - plotly
  - plotly-orca==1.3.1
  - pip:
      - ipywidgets
      - kmapper
      - hypernetx
      - psutil 
      - requests

